context:
  version: 3.1.0

package:
  name: gel-python
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/g/gel/gel-${{ version }}.tar.gz
    sha256: 3bb0b21167e00c976675a7d5dd73c21002e659651bf9de7fa46cd418bfa3eb85

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - edgedb-py = gel.codegen.cli:main
      - gel = gel.cli:main
      - gel-orm = gel.orm.cli:main
      - gel-py = gel.codegen.cli:main

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - if: win
      then:
        - certifi >=2021.5.30
    - httpx ~=0.27.0 # extra == "ai"
    - httpx-sse ~=0.4.0 # extra == "ai"

tests:
  - python:
      imports:
        - gel
      pip_check: true
  - script:
      - edgedb-py --help
      - gel --help
      - gel-orm --help
      - gel-py --help

about:
  homepage: https://github.com/geldata/gel-python/
  summary: Official Gel Python Driver
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
